name: Publish to GitHub Pages

on:
  push:
    branches:
      - main

env:
  VITE_API_URL: 'api-uno.venashial.games'
  VITE_USE_HTTPS: 'true'

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Cache pnpm modules
          uses: actions/cache@v2
          with:
            path: ~/.pnpm-store
            key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
            restore-keys: |
              ${{ runner.os }}-

        - name: Set up pnpm
          uses: pnpm/action-setup@v2.0.1
          with:
            version: 6.18.0
            run_install: true

        - name: Build website
          run: pnpm build

        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./build